### ISSUE TITLE
Cannot Create a New Form in Mobuis 4.1.0

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/app-mobius-forms#33] opened 2020-08-08 21:29 UTC
This is a fresh new install of DNN v9.06.01, 2sxc v11.04, and Mobius 4.1 (I also let 2sxc install the latest Contact App, I assume that is 11.03, but I can't seem to find where it's version number might be hidden).

I tried following the Azing recipe, but I guess that is out of date. My goal was simple, I wanted to NOT modify the existing Views and create a new form that had SenderPhone and not Subject.
 
I added SenderPhone to the existing Content Type, "ContentSimple" - same as SenderName, everything default.
 
I made an exact copy of "Confact Form.cshtml" - meaning I copied each of the files in the root, /staging, and /live and gave all 3 the same name, "Contact-Form-basic.cshtml.

The only change I made to the /staging copy start at line 16, removing Subject and adding SenderPhone like this:
```
  <div class="mobius-form">
    @FieldBuilder.Text("SenderName", true)
    @FieldBuilder.EMail("SenderMail", true)
    @FieldBuilder.Text("SenderPhone", false)
    @FieldBuilder.Multiline("Message", true)
```

The form displays as expected:
<img src="https://user-images.githubusercontent.com/653301/89719918-c8784800-d992-11ea-9681-693fb0ab13b8.png" width="400" />

No matter what I do, when I submit, I end up stuck with this error on line 7 in /staging/shared/_Toolbar.cshtml
7  `var workflow = AsList(App.Data["Workflow"]).Where(w => w.WorkflowId == WorkflowId).FirstOrDefault();`
```
Message:The given key was not present in the dictionary.

StackTrace:

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ASP._Page_Portals_0_2sxc_Mobius_Forms_staging_shared__Toolbar_cshtml.Execute() in c:\HostingSpaces\METZ\midwestaccidentreconstruction.com\www\Portals\0\2sxc\Mobius Forms\staging\shared\_Toolbar.cshtml:line 7
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.WebPages.WebPageBase.<>c__DisplayClass7.<RenderPageCore>b__6(TextWriter writer)
   at System.Web.WebPages.WebPageBase.Write(HelperResult result)
   at ASP._Page_Portals_0_2sxc_Mobius_Forms_staging__Contact__Form__basic_cshtml.Execute() in c:\HostingSpaces\METZ\midwestaccidentreconstruction.com\www\Portals\0\2sxc\Mobius Forms\staging\_Contact__Form--basic.cshtml:line 13
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
```

I foreach'd through the collection in App.Data and there is nothing named "WorkFlow"
 
It may or may not be related, but I also noticed that in the Views, the names are not appearing for the Content-Types, just the GUIDs, this screen clip is from the unmodified (your) View named "Contact Form":
![image](https://user-images.githubusercontent.com/653301/89720045-e4301e00-d993-11ea-8b22-37d1e5d80f3c.png)

This is a fresh new install of DNN v9.06.01, 2sxc v11.04, and Mobius 4.1 (I also let 2sxc install the latest Contact App, I assume that is 11.03, but I can't seem to find where it's version number might be hidden).

**Comment by iJungleboy** [comment] 2020-08-10 06:01
First of all, the view-showing-guid is an issue in 2sxc 11.04 https://github.com/2sic/2sxc/issues/2145 - it's already fixed and will be in 11.05.

**Comment by iJungleboy** [comment] 2020-08-10 06:02
@ropalko can you pls check what's wrong and if necessary also update docs?

**Comment by jeremy-farrance** [comment] 2020-08-12 02:17
Anything?

**Comment by iJungleboy** [comment] 2020-08-12 07:56
@jeremy-farrance we'll look into this asap. @ropalko was on vacation till yesterday, so he's just getting up to speed again :)

**Comment by jeremy-farrance** [comment] 2020-08-19 15:27
Bump.

**Comment by jeremy-farrance** [comment] 2020-08-26 15:00
Bump?

**Comment by ropalko** [comment] 2020-08-27 14:47
Hello @jeremy-farrance, sorry for the late reply.
I updated the Checklist on Azing: [Customize Mobius Forms](https://azing.org/2sxc/r/l38Ibz7L)

I tried to reproduce your problem, but I don't get the error message you mentioned.

So your _Contact-form-basic.cshtml shoul look like this:
```
@inherits ToSic.Sxc.Dnn.RazorComponent
@using System.Linq
@using Connect.Koi
@using Dynlist = System.Collections.Generic.IEnumerable<dynamic>;
@{
  var Edition = (Dnn.User.IsSuperUser ? "staging" : "live");
  var workflowId = "ContactDefault";
  var FieldBuilder = CreateInstance("shared/_Field Builders.cshtml");
  var helpers = CreateInstance("shared/_Helpers.cshtml");
}

<div class="@helpers.WrapperClasses(Content)" data-webservice="app/auto/@Edition/api/Form/ProcessForm?workflowId=@workflowId">
  @RenderPage("shared/_Toolbar.cshtml", new { Content = Content, WorkflowId = workflowId })

  <div class="mobius-form">
    @FieldBuilder.Text("SenderName", true)
    @FieldBuilder.EMail("SenderMail", true)
    @FieldBuilder.Text("SenderPhone", false)
    @FieldBuilder.Multiline("Message", true)
    
    @if(App.Settings.TermsEnabled) {
      @RenderPage("shared/_Terms.cshtml")
    }

    @if(App.Settings.GdprEnabled) {
      @RenderPage("shared/_GDPR.cshtml")
    }

    @* Recaptcha *@
    @if(Content.Recaptcha ?? false) {
      @RenderPage("shared/_Recaptcha.cshtml")
    }

    @* Messages / Send Button *@
    @RenderPage("shared/_Submit with Messages.cshtml")
  </div>
</div>

@RenderPage("shared/_Assets.cshtml")
```
And your view settings like this:
![image](https://user-images.githubusercontent.com/921493/91457685-eb589680-e884-11ea-9d4c-567564f0d9c9.png)

Can you please check if you System Workflow Configuration looks like this:
![image](https://user-images.githubusercontent.com/921493/91457550-c106d900-e884-11ea-8beb-7694c986d0ba.png)

**Comment by jeremy-farrance** [comment] 2020-08-28 16:46
I checked everything above very carefully, it all matches - except for the last screenshot. Are you saying there should be a Content-Type with the name "System Workflow Configuration" ?? If yes, then that is what is missing in my install/instance. In the install package, where can I find what I would need to import to get that created? Or is it safe to just re-import the whole thing?

**Comment by ropalko** [comment] 2020-09-01 12:16
Hello @jeremy-farrance, thats really strange.
These are the content types you should have:
![image](https://user-images.githubusercontent.com/921493/91850015-2e3bb500-ec5d-11ea-8b30-6618c2ed2465.png)

Maybe something went wrong during the installation. I would download the latest release and try to install it under a new name.

**Comment by jeremy-farrance** [comment] 2020-09-01 13:44
Are there instructions on how to install and app under a new name? Don't think I've ever done or noticed that. I there a proper way to completely delete an app, Content Types and all so it can be cleanly re-installed?

**Comment by ropalko** [comment] 2020-09-01 14:29
When you try to install 2sxc asks you that there is a other version and which name the new should have.
You can delete the app when you open the app managment:
![image](https://user-images.githubusercontent.com/921493/91864131-2b968b00-ec70-11ea-9e3a-3b478f7d6ab9.png)
![image](https://user-images.githubusercontent.com/921493/91864206-3c470100-ec70-11ea-9c20-04f07d7e6d47.png)

**Comment by jeremy-farrance** [comment] 2020-09-01 14:56
Ok, so at this point I am confused. This was a clean DNN install with 2sxc 11.03, then 11.04. On July 27 I let 2sxc install Mobius and News for me... it said it would install the latest versions. I had read the blogs and even double checked to see what versions were available and both News and Mobius were new v4.x from early May releases. So I let 2sxc install the apps for me. Embarrassingly I now discover that both the installed versions were v3.x. How did that happen? Why didn't the installer use the new versions that had been released more than 2 months ago?

**Comment by iJungleboy** [comment] 2020-09-02 05:52
@jeremy-farrance When we release new apps they don't automatically land in the auto-installer. We do this manually. On large reworks (like on Mobius) we delay it by quite a while to be sure that it works in the wild, as the auto-installer is used by newbies, and we want to be sure they don't run into problems.

**Closed by iJungleboy** 2020-09-02 05:52 UTC

**Comment by jeremy-farrance** [comment] 2020-09-02 14:31
> @jeremy-farrance When we release new apps they don't automatically land in the auto-installer. We do this manually. On large reworks (like on Mobius) we delay it by quite a while to be sure that it works in the wild, as the auto-installer is used by newbies, and we want to be sure they don't run into problems.

I appreciate that more recent versions seem to be making it easier to discover the actual version number that is installed. Hopefully that gets even better?
